basePath: Workspace.xcworkspace
testPlan: TestPlan.xctestplan
extra:
  targetsFiles:
    MyProjectName:SomeTarget:
    - Path/File.swift
    - Path/Subfolder
  dependencies:
    MyProjectName:SomeTarget:
    - MyProjectName:SecondTarget
    - Package:APackage
